### ISSUE TITLE
My ToDo List

### ISSUE THREAD

**Issue by Bencey** [Bencey/docker-stack#1]
- [ ] Sort out performance issues when VMs are installed on ZFS pool (Prox1)
- [ ] Finish setting up failover between prox1 & prox2
- [ ] Setup prox2 nodes (Node4, 5, 6)
- [ ] Setup system alerts

## System Alert List
- [ ] When node is offline
- [ ] When site / services is offline
- [ ] Ram Usage
- [ ] CPU Usage
